sudo: false

language: ruby

before_install:
  - gem install bundler

after_success:
  - coveralls

matrix:
  include:
    - rvm: 2.4.1
      script:
        - bundle exec danger
    - rvm: 2.4.1
    - rvm: 2.3.4
    - rvm: 2.2.7
    - rvm: ruby-head
    - rvm: jruby-9.1.9.0
    - rvm: jruby-head
    - rvm: rbx-2

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.9.0
    - rvm: jruby-head
    - rvm: rbx-2
